trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:

- script: eng\common\cibuild.cmd
    -configuration Debug
    -preparemachine
    -TestArgs /p:ServiceUri=wcfcoresrv3.redmond.corp.microsoft.com/WcfService38 /p:Root_Certificate_Installed=true /p:Client_Certificate_Installed=true /p:SSL_Available=true
    /p:Test=false
  displayName: Windows Build / Publish
