trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'
  
resources:
  containers:
  - container: web_hosted_service_container
    image: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'
    #image: 'mcr.microsoft.com/dotnet/framework/wcf:latest'
    #options: --entrypoint "./src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd 38" 
    options: --entrypoint "git clone https://github.com/afifi-ins/wcf.git" 
    #; wcf\src\System.Private.ServiceModel\tools\scripts\SetupWcfIISHostedService.cmd 38
  - container: windows_container
    image: 'mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019'
    #image: 'mcr.microsoft.com/dotnet/sdk:6.0'
    
  
stages:
- stage: Build_Service_stage
  displayName: Build and Run WCF Services
  jobs:
  - job: list_images
    displayName: list docker images
    steps:
    - script: docker image list

  - job: Build_IIS_Service_job
    displayName: Build and run web hosted service
    services:
      web_hosted_service: web_hosted_service_container
    # steps:
    # - checkout: self

  - job: Build_Selfhosted_Service_job
    displayName: Build and run self-hosted service
    steps:
    - bash: echo "A"

- stage: Run_WCF_Tests
  displayName: Build and Run WCF Tests
  jobs:
  - job: Windows_release_job
    displayName: Windows Release tests
    container: windows_container
    # steps:
    # - script: eng\common\cibuild.cmd 
    #     -configuration Debug
    #     -preparemachine
    #     /p:ServiceUri=wcfcoresrv3.redmond.corp.microsoft.com/WcfService38 /p:Root_Certificate_Installed=true /p:Client_Certificate_Installed=true /p:SSL_Available=true
    #     /p:Test=true /p:IntegrationTest=true /p:Pack=true /p:Publish=true
    #   displayName: Run tests

  - job: Windows_debug_job
    displayName: Windows Debug tests
    steps:
    - bash: echo "A"

  - job: Linux_release_job
    displayName: Linux Release tests
    steps:
    - bash: echo "A"

  - job: Linux_debug_job
    displayName: Linux Debug tests
    steps:
    - bash: echo "A"