trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo build
    ls
    sh ./build.sh
  displayName: 'Run a multi-line script'
