trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo build
    build.cmd
  displayName: 'Run a multi-line script'
